/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var c=Object.defineProperty;var m=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var x=Object.prototype.hasOwnProperty;var u=(t,e)=>{for(var r in e)c(t,r,{get:e[r],enumerable:!0})},P=(t,e,r,s)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of p(e))!x.call(t,o)&&o!==r&&c(t,o,{get:()=>e[o],enumerable:!(s=m(e,o))||s.enumerable});return t};var k=t=>P(c({},"__esModule",{value:!0}),t);var C={};u(C,{default:()=>i});module.exports=k(C);var f=require("obsidian"),i=class extends f.Plugin{async onload(){this.registerMarkdownPostProcessor((e,r)=>{let s=r.getSectionInfo(e);if(!s)return;let o=s.text.split(`
`),l=0;for(let n=s.lineStart-1;n>=0&&o[n].trim()==="";n--)l++;let d=l-1;if(!(d<=0))for(let n=0;n<d;n++){let a=document.createElement("div");a.className="preserve-blank-line",a.appendChild(document.createTextNode("\xA0")),e.insertBefore(a,e.firstChild)}})}};
